### ISSUE TITLE
If disengage the AP through STICK FORCE, it freezes the ROLL COMMAND

### ISSUE THREAD

**Issue by malamem** [08jne01/community-a4e-c#18]
**Describe the bug**
If disengage the AP through STICK FORCE, it freezes the ROLL COMMAND at the position and need to trim the aircraft back to resume normal flight.

**To Reproduce**
1. Set AP ON
2. Move stick for any side until AP disconnects
3. Survive and Re-trim the ACFT

**Software Information (please complete the following information):**
 - DCS Version: 2.5.6.49798
 - A-4E Version EFM DEV

**Comment by 08jne01** [comment]
See issue #13.
