### ISSUE TITLE
Engine works normally when flying inverted

### ISSUE THREAD

**Issue by malamem** [08jne01/community-a4e-c#19]
**Describe the bug**
It seems that the inverted flying flameout was not set yet.

**To Reproduce**
1. Take off
2. Fly inverted long time
3. Pull negative G's

**Expected behavior**
Engine Flameout after some time flying inverted. 

**Software Information (please complete the following information):**
 - DCS Version: 2.5.6.49.798
 - A-4E Version EFM DEV

**Comment by 08jne01** [comment]
Engine still needs rework see issue #7.
