### ISSUE TITLE
OXYGEN SYSTEM SEEMS TO NOT BE SET YET

### ISSUE THREAD

**Issue by malamem** [08jne01/community-a4e-c#21]
**Describe the bug**
 I switched the OXYGEN OFF when at FL350 and nothing happened for a long time.

**To Reproduce**
1. take off and climb to FL350
2. SWITCH the Oxygen to OFF
3. Wait

**Expected behavior**
It is expected to have some HYPOXIA for the pilot.

**Screenshots**

**Software Information (please complete the following information):**
 - DCS Version: 2.5.6.49.798
 - A-4E Version EFM DEV

**Comment by 08jne01** [comment]
Duplicate: see issue #14.
