### ISSUE TITLE
UNABLE TO GET HOOKED IN SAO PAULO CARRIER

### ISSUE THREAD

**Issue by malamem** [08jne01/community-a4e-c#22]
**Describe the bug**
Tried a launch from Sao Paulo carrier and altough received the text "You are hooked...", When I set FULL POWER it accelerated normally like no HOOKED.

**To Reproduce**
1. Set a mission with A-4 starting from ramp on A-12 NAe Sao Paulo
2. Taxi to Shuttle or anyplace
3. Hook through A-4 system and salute

**Expected behavior**
After the message of being hooked in, the acft should remain static and get launched after SALUTE command.

**Software Information (please complete the following information):**
 - DCS Version: 2.5.6.49798
 - A-4E Version EFM DEV

**Comment by 08jne01** [comment]
See issue #5.
