### ISSUE TITLE
EMERGENCY LDG GEAR DOES NOT WORK

### ISSUE THREAD

**Issue by malamem** [08jne01/community-a4e-c#26]
**Describe the bug**
With ENGINES SHUT DOWN and NO EMERGENCY GENERATOR, we are unable to deploy the LDG by emergency.

**To Reproduce**
1. Shutdown engine inflight
2. Lower the gear handle
3. Pull the emergency LDG HANDLE

**Expected behavior**
The emergency LDG GEAR deployment system needs to work with NO ELECTRICAL supply and  even with the LDG GEAR HANDLE at UP Position.

**Software Information (please complete the following information):**
 - DCS Version: 2.5.6.49798
 - A-4E Version EFM DEV

**Comment by 08jne01** [comment]
In order to deploy gear with the emergency handle. You must have no hydraulics and the gear handle must be down. Then you press the emergency release. This is how the current A-4 is coded at least.

**Comment by 08jne01** [comment]
Check natops for correct procedure.

**Comment by 08jne01** [comment]
Current implementation consistent with natops.
