### ISSUE TITLE
Spawned as "Take off from runway" plane drifts to one side 5deg

### ISSUE THREAD

**Issue by NeroDCS** [08jne01/community-a4e-c#33]
i noticed a strange behavior when "taking of from some runways" (spawned plane as take of from RW)
without input except throttle the Plane steers of to one side until precisly 5deg of centerline: but not consitence left or right, see table:

Map: Persian Golf
```
Airport                   Runway heading                      Heading of Plane after a few seconds of accelerating

Ras ak Khakmah            345                                   340 (drift left)
Al minhad AB              270                                   275 (drift right)
Al Ain International      188                                   183  (drift left)
```

**Comment by NeroDCS** [comment]
totaly forgot: its a fresh mission with no wind.

**Comment by 08jne01** [comment]
This is likely the suspension moving the free-castoring nose wheel when the plane falls onto the ground after start. Try doing the same but hold the nosewheel steering down this way it will force the nosewheel to be straight.

**Comment by NeroDCS** [comment]
totaly forgot to respond, yes that solves the problem.
