### ISSUE TITLE
DCS Crashes when Eject on ground

### ISSUE THREAD

**Issue by malamem** [08jne01/community-a4e-c#34]
CALLSTACK:

# -------------- 20200708-123341 --------------
DCS/2.5.6.49798 (x86_64; Windows NT 10.0.18363)
C:\Program Files\Eagle Dynamics\DCS World OpenBeta\bin\CockpitBase.dll
# C0000005 ACCESS_VIOLATION at 652B99E9 00:00000000
SymInit: Symbol-SearchPath: '.', symOptions: 534, UserName: 'klebe'
OS-Version: 10.0.18363 () 0x100-0x1
0x00000000001499E9 (CockpitBase): ed_cockpit_set_action_digital + 0x9
0x0000000000001EA6 (A-4E-C): ed_fm_simulate + 0x46
0x0000000000513D9C (DCS): woLA::loadNewInputLayout + 0x12082C
0x00000000000A9385 (FMBase): EagleFM::AerodyneFM::simulate + 0x425
0x0000000000670139 (DCS): woLA::loadNewInputLayout + 0x27CBC9
0x0000000000505214 (DCS): woLA::loadNewInputLayout + 0x111CA4
0x0000000000504D1F (DCS): woLA::loadNewInputLayout + 0x1117AF
0x0000000000003AE4 (World): wSimTrace::CommandsTraceDiscreteIsOn + 0x504
0x0000000000003F8D (World): wSimCalendar::DoActionsUntil + 0x1FD
0x00000000006FFD2F (DCS): woLA::loadNewInputLayout + 0x30C7BF
0x0000000000710C13 (DCS): dDispatcher::InitDatabase + 0xDC43
0x00000000006E7154 (DCS): woLA::loadNewInputLayout + 0x2F3BE4
0x00000000006E7519 (DCS): woLA::loadNewInputLayout + 0x2F3FA9
0x0000000001597A21 (DCS): AmdPowerXpressRequestHighPerformance + 0x9E8A1D
0x00000000008C9F2E (DCS): uiAsyncNet::onGameStop + 0x682FE
0x0000000000017BD4 (KERNEL32): BaseThreadInitThunk + 0x14
0x000000000006CE51 (ntdll): RtlUserThreadStart + 0x21

**Comment by 08jne01** [comment]
This has been fixed now.
